/**
 * A curated list of ~100 of the largest / most-searched US-listed companies
 * (symbol + company name). It powers the search bar's *instant* results: these
 * match locally with zero network latency, so typing "apple" or "AAPL" surfaces
 * Apple Inc. immediately, before (and alongside) the debounced yfinance search.
 *
 * This is only a fast-path index for autocomplete. The instrument detail page
 * still fetches everything (price, chart, stats) live from lens-api / yfinance,
 * so any ticker not in this list is fully reachable via the remote search.
 *
 * Ordering is roughly by size so higher-profile names rank first on ties.
 */
export interface TopTicker {
  symbol: string
  name: string
}

export const TOP_TICKERS: TopTicker[] = [
  { symbol: 'AAPL', name: 'Apple Inc.' },
  { symbol: 'MSFT', name: 'Microsoft Corporation' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. (Google) Class A' },
  { symbol: 'GOOG', name: 'Alphabet Inc. (Google) Class C' },
  { symbol: 'AMZN', name: 'Amazon.com, Inc.' },
  { symbol: 'META', name: 'Meta Platforms, Inc. (Facebook)' },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway Inc. Class B' },
  { symbol: 'TSLA', name: 'Tesla, Inc.' },
  { symbol: 'AVGO', name: 'Broadcom Inc.' },
  { symbol: 'LLY', name: 'Eli Lilly and Company' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.' },
  { symbol: 'V', name: 'Visa Inc.' },
  { symbol: 'XOM', name: 'Exxon Mobil Corporation' },
  { symbol: 'UNH', name: 'UnitedHealth Group Incorporated' },
  { symbol: 'MA', name: 'Mastercard Incorporated' },
  { symbol: 'COST', name: 'Costco Wholesale Corporation' },
  { symbol: 'HD', name: 'The Home Depot, Inc.' },
  { symbol: 'PG', name: 'The Procter & Gamble Company' },
  { symbol: 'JNJ', name: 'Johnson & Johnson' },
  { symbol: 'WMT', name: 'Walmart Inc.' },
  { symbol: 'NFLX', name: 'Netflix, Inc.' },
  { symbol: 'ABBV', name: 'AbbVie Inc.' },
  { symbol: 'BAC', name: 'Bank of America Corporation' },
  { symbol: 'CRM', name: 'Salesforce, Inc.' },
  { symbol: 'ORCL', name: 'Oracle Corporation' },
  { symbol: 'CVX', name: 'Chevron Corporation' },
  { symbol: 'KO', name: 'The Coca-Cola Company' },
  { symbol: 'AMD', name: 'Advanced Micro Devices, Inc.' },
  { symbol: 'PEP', name: 'PepsiCo, Inc.' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc.' },
  { symbol: 'WFC', name: 'Wells Fargo & Company' },
  { symbol: 'CSCO', name: 'Cisco Systems, Inc.' },
  { symbol: 'MCD', name: "McDonald's Corporation" },
  { symbol: 'ADBE', name: 'Adobe Inc.' },
  { symbol: 'ACN', name: 'Accenture plc' },
  { symbol: 'ABT', name: 'Abbott Laboratories' },
  { symbol: 'LIN', name: 'Linde plc' },
  { symbol: 'GE', name: 'GE Aerospace' },
  { symbol: 'DIS', name: 'The Walt Disney Company' },
  { symbol: 'INTC', name: 'Intel Corporation' },
  { symbol: 'IBM', name: 'International Business Machines Corporation' },
  { symbol: 'QCOM', name: 'QUALCOMM Incorporated' },
  { symbol: 'TXN', name: 'Texas Instruments Incorporated' },
  { symbol: 'CAT', name: 'Caterpillar Inc.' },
  { symbol: 'VZ', name: 'Verizon Communications Inc.' },
  { symbol: 'DHR', name: 'Danaher Corporation' },
  { symbol: 'PFE', name: 'Pfizer Inc.' },
  { symbol: 'AMGN', name: 'Amgen Inc.' },
  { symbol: 'PM', name: 'Philip Morris International Inc.' },
  { symbol: 'NKE', name: 'NIKE, Inc.' },
  { symbol: 'NOW', name: 'ServiceNow, Inc.' },
  { symbol: 'INTU', name: 'Intuit Inc.' },
  { symbol: 'UNP', name: 'Union Pacific Corporation' },
  { symbol: 'RTX', name: 'RTX Corporation (Raytheon)' },
  { symbol: 'HON', name: 'Honeywell International Inc.' },
  { symbol: 'SPGI', name: 'S&P Global Inc.' },
  { symbol: 'GS', name: 'The Goldman Sachs Group, Inc.' },
  { symbol: 'AMAT', name: 'Applied Materials, Inc.' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.' },
  { symbol: 'LOW', name: "Lowe's Companies, Inc." },
  { symbol: 'ISRG', name: 'Intuitive Surgical, Inc.' },
  { symbol: 'T', name: 'AT&T Inc.' },
  { symbol: 'AXP', name: 'American Express Company' },
  { symbol: 'BLK', name: 'BlackRock, Inc.' },
  { symbol: 'ELV', name: 'Elevance Health, Inc.' },
  { symbol: 'PLTR', name: 'Palantir Technologies Inc.' },
  { symbol: 'SYK', name: 'Stryker Corporation' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Incorporated' },
  { symbol: 'PGR', name: 'The Progressive Corporation' },
  { symbol: 'C', name: 'Citigroup Inc.' },
  { symbol: 'MDT', name: 'Medtronic plc' },
  { symbol: 'BSX', name: 'Boston Scientific Corporation' },
  { symbol: 'MU', name: 'Micron Technology, Inc.' },
  { symbol: 'ADP', name: 'Automatic Data Processing, Inc.' },
  { symbol: 'TJX', name: 'The TJX Companies, Inc.' },
  { symbol: 'SCHW', name: 'The Charles Schwab Corporation' },
  { symbol: 'LRCX', name: 'Lam Research Corporation' },
  { symbol: 'GILD', name: 'Gilead Sciences, Inc.' },
  { symbol: 'BA', name: 'The Boeing Company' },
  { symbol: 'MMC', name: 'Marsh & McLennan Companies, Inc.' },
  { symbol: 'ETN', name: 'Eaton Corporation plc' },
  { symbol: 'KLAC', name: 'KLA Corporation' },
  { symbol: 'DE', name: 'Deere & Company' },
  { symbol: 'PANW', name: 'Palo Alto Networks, Inc.' },
  { symbol: 'CB', name: 'Chubb Limited' },
  { symbol: 'SBUX', name: 'Starbucks Corporation' },
  { symbol: 'ADI', name: 'Analog Devices, Inc.' },
  { symbol: 'MO', name: 'Altria Group, Inc.' },
  { symbol: 'CMCSA', name: 'Comcast Corporation' },
  { symbol: 'ANET', name: 'Arista Networks, Inc.' },
  { symbol: 'UBER', name: 'Uber Technologies, Inc.' },
  { symbol: 'GEV', name: 'GE Vernova Inc.' },
  { symbol: 'MDLZ', name: 'Mondelez International, Inc.' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals, Inc.' },
  { symbol: 'CI', name: 'The Cigna Group' },
  { symbol: 'FI', name: 'Fiserv, Inc.' },
  { symbol: 'SO', name: 'The Southern Company' },
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF Trust' },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust (Nasdaq-100 ETF)' },
  { symbol: 'VOO', name: 'Vanguard S&P 500 ETF' },
]
